id: I3CE94CD4
legacy_id: P005431
ocr_import_info:
  bdrc_scan_id: W3CN5330
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T19:03:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T12:08:14.697592+00:00'
last_modified: 2022-08-27 20:08:28.810550
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5330
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5330
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྟུང་བ་སྡེ་ལྔའི་སྐབས་ཀྱི་གླེང་གཞི་དང་དགག་བྱ་ངོ་བོ་ལྟུང་བའི་ཡན་ལག་རྣམས་མདོར་ཙམ་བཀོད་པ་བློ་གསར་གཞོན་ནུའི་མགུལ་རྒྱན།
  author: འབྲི་གྲྭ་ཐུབ་བསྟན་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.9470445321204719
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN5332:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5332
      total_pages: 214
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5332.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9470445321204719
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
