id: I3CE94CD4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:04:18+00:00'
last_modified: '2022-06-08T03:02:34.139305+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5330
  title: ལྟུང་བ་སྡེ་ལྔའི་སྐབས་ཀྱི་གླེང་གཞི་དང་དགག་བྱ་ངོ་བོ་ལྟུང་བའི་ཡན་ལག་རྣམས་མདོར་ཙམ་བཀོད་པ་བློ་གསར་གཞོན་ནུའི་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EC4F:
      image_group_id: I3CN5332
      title: ''
      total_pages: 214
      order: 1
      base_file: EC4F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
