id: P005431
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5330
  title: ལྟུང་བ་སྡེ་ལྔའི་སྐབས་ཀྱི་གླེང་གཞི་དང་དགག་བྱ་ངོ་བོ་ལྟུང་བའི་ཡན་ལག་རྣམས་མདོར་ཙམ་བཀོད་པ་བློ་གསར་གཞོན་ནུའི་མགུལ་རྒྱན།
  author: ''
  volumes:
    645c81b1d98c4121bac61f014a364aea:
      image_group_id: I3CN5332
      title: ''
      volume_number: 1
      total_pages: 214
